---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Create the {{environment_name}} ui-docs stack
      local_action:
        module: cloudformation
        region: ca-central-1
        stack_name: ui-{{environment_name}}-docs
        state: present
        template: template.yml
        template_parameters:
          AcmArn: "{{aws_acm_arn}}"
          Enabled: "{{enabled}}"
          Environment: "{{environment_name}}"
          RootStackName: plt-{{environment_name}}
