AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Riipen UI Documentation stack.
Parameters:
  Environment:
    Type: String
    Description: >
      The environment which to launch the service in
    Default: staging
  RootStackName:
    Type: String
    Description: >
      Name of the CloudFormation stack to insert this service in
  AcmArn:
    Type: String
    Description: >
      The ARN of the AWS ACM certificate to use in the cloud configuration
  Enabled:
    Type: String
    Description: >
      Whether or not the site is live.
    Default: false
  ACLId:
    Type: String
    Description: >
      A unique identifier that specifies the AWS WAF web ACL, if any, to associate with this distribution.
    Default: ""
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ui-${Environment}-docs
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          -
            Action: 
              - "s3:GetObject"
            Effect: "Allow"
            Resource: 
              Fn::Join: 
                - ""
                - 
                  - "arn:aws:s3:::"
                  - 
                    !Sub ui-${Environment}-docs
                  - "/*"
            Principal: "*"
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub
            - ui.${DomainName}
            - DomainName:
                Fn::ImportValue: !Sub ${RootStackName}-domain
        Comment: !Sub ui-${Environment}-docs hosting
        DefaultCacheBehavior:
          AllowedMethods:
              - GET
              - HEAD
          CachedMethods:
              - GET
              - HEAD
          Compress: false
          DefaultTTL: 0
          ForwardedValues:
            Cookies: 
              Forward: none
            QueryString: true
          MaxTTL: 0
          MinTTL: 0
          TargetOriginId: !Sub ui-${Environment}-docs
          ViewerProtocolPolicy: redirect-to-https
        Enabled: !Ref Enabled
        HttpVersion: http2
        IPV6Enabled: false
        Origins:
          -
            ConnectionAttempts: 3
            ConnectionTimeout: 10
            CustomOriginConfig: 
              OriginProtocolPolicy: match-viewer
              OriginSSLProtocols: 
                - TLSv1.1
            DomainName: !GetAtt S3Bucket.WebsiteURL
            Id: !Sub ui-${Environment}-docs
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmArn
          MinimumProtocolVersion: TLSv1.1_2016
          SslSupportMethod: sni-only
        WebACLId: !Ref ACLId
  Route53:
    Type: AWS::Route53::RecordSet
    Properties: 
      AliasTarget: 
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      HostedZoneId: Z32BLFYZOEYOHS
      Name: !Sub
        - ui.${DomainName}
        - DomainName:
            Fn::ImportValue: !Sub ${RootStackName}-domain
      Type: A




        



  